- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
    
- name: Doxygen Action
  uses: mattnotmitt/doxygen-action@v1.3.1
